#!/bin/sh

. /etc/fos/config/fos_shell_settings

while :
do
    cpu=$(sb-cpu)
    cputemp=$(sb-cputemp)
    cpuspeed=$(sb-cpuspeed)
    bat=$(sb-battery)
    clock=$(sb-clock)
    printf "%s | %s | %s | %s | %s\n" "$cpu" "$cpuspeed" "$cputemp" "$bat" "$clock"
    sleep 2
done
